### PR TITLE
skip track hypotheses with momentum nan

### LINKED ISSUE #938: Segfault in DChargedTrackHypothesis_factory::Correct_CDC_dEdx_amp
In the currently running analysis launch, I see segmentation faults in DChargedTrackHypothesis_factory::Correct_CDC_dEdx_amp

The problem is repeatable, and occurs when using only monitoring hists. Examples for problematic files:
`/cache/halld/RunPeriod-2019-11/recon/ver01/REST/071881/dana_rest_071881_173.hddm` after ~180k events
`/cache/halld/RunPeriod-2019-11/recon/ver01/REST/071889/dana_rest_071889_077.hddm` after ~639k events
`/cache/halld/RunPeriod-2019-11/recon/ver01/REST/071922/dana_rest_071922_149.hddm` after ~779k events
`/cache/halld/RunPeriod-2019-11/recon/ver01/REST/071926/dana_rest_071926_267.hddm` after ~622k events

With version_6.1.1.xml, the issue can be reproduced with this command:
`hd_root -PPLUGINS=monitoring_hists -PNTHREADS=32 $FILE`

### PR DESCRIPTION
**Pull request by nsjarvis**
This is to fix [issue 938](https://github.com/JeffersonLab/halld_recon/issues/938).

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_ignore_nans/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_ignore_nans/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_ignore_nans/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_ignore_nans/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_ignore_nans/make_nsj_ignore_nans.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_ignore_nans/make_nsj_ignore_nans.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_ignore_nans/report_nsj_ignore_nans.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_ignore_nans/report_nsj_ignore_nans.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_ignore_nans

File: src/libraries/HDDM/DEventSourceREST.cc [hunk 1]
```diff
@@ -1388,19 +1388,32 @@ bool DEventSourceREST::Extract_DTrackTimeBased(hddm_r::HDDM *record,
...
+      }
+    
       DTrackTimeBased *tra = new DTrackTimeBased();
       tra->trackid = 0;
       tra->candidateid = iter->getCandidateId();
       Particle_t ptype = iter->getPtype();
       tra->setPID(ptype);
 
-      const hddm_r::TrackFit &fit = iter->getTrackFit();
+      //      const hddm_r::TrackFit &fit = iter->getTrackFit();
```
Comment (aaust) [inline src/libraries/HDDM/DEventSourceREST.cc:1409]: Can you please remove this line instead of commenting it out?

**Review by aaust — CHANGES_REQUESTED** [review]

File: src/libraries/HDDM/DEventSourceREST.cc (hunk 1 above)
Comment (nsjarvis) [reply src/libraries/HDDM/DEventSourceREST.cc]: Done

**Review by aaust — APPROVED** [review]
Thanks, it works well
